version: '3.1'
services:
  mysql:
    image: mariadb:latest
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: tempdata
      MYSQL_ROOT_PASSWORD: root

