FROM grafana/grafana:5.0.0

COPY grafana-mysql.yml /etc/grafana/provisioning/datasources/datasource.yml
COPY dashboard.json /dashboards/dashboard.json
COPY dashboards.yml /etc/grafana/provisioning/dashboards/dashboards.yml


