apiVersion: 1

datasources:
  - name: mysql
    type: mysql
    access: proxy
    url: '${MYSQL_HOST}'
    database: '${MYSQL_DATABASE}'
    user: '${MYSQL_USERNAME}'
    password: '${MYSQL_PASSWORD}'
