version: '3.1'
services:
  mysql:
    image: mariadb:latest
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: tempdata
      MYSQL_ROOT_PASSWORD: root
      
  grafana:
    image: grafana/grafana:5.0.0
    ports:
      - 8081:3000
    volumes:
      - ./grafana-mysql.yml:/etc/grafana/provisioning/datasources/datasource.yml

